/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myjava1;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 2022127
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        theHeadOfficeBranch = new Branch();
        //theHeadOfficeBranch.Edit( "working hours\n"," sort code\n" , " manager\n");
        theHeadOfficeBranch.LoadFromFile();
        theAddress = new IAddress();
        theAddress.Edit("manager\n", "\n", "\n", "\n", "\n", "\n", "\n", 0);

        theUser = new User();

        jCalcTabInMemory = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1);
        jHeadOfficeTabInMemory = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1);
        jMainTabbedPane.setSelectedIndex(0);
        jEditHeadOfficeTabInMemory = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1);
        jEditClientTabInMemory = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1);
        jClientInfoTabInMemory = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1);

        theUser = new User();

        this.clientsList = new CustomerList();
        this.clientsList.create();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStatusPanel = new javax.swing.JPanel();
        jStatusMessageLabel = new javax.swing.JLabel();
        jStatusAnimationLabel = new javax.swing.JLabel();
        jProgressCompletionBar = new javax.swing.JProgressBar();
        jMainPanel = new javax.swing.JPanel();
        jMainTabbedPane = new javax.swing.JTabbedPane();
        jLoginPanel = new javax.swing.JPanel();
        jNameLabel = new javax.swing.JLabel();
        jNameTextField = new javax.swing.JTextField();
        jLoginButton = new javax.swing.JButton();
        jPasswordLabel = new javax.swing.JLabel();
        jRegisterButton = new javax.swing.JButton();
        jPasswordTextField = new javax.swing.JTextField();
        jPositionLabel = new javax.swing.JLabel();
        jRoleBox = new javax.swing.JComboBox<>();
        jCalculatorPanel = new javax.swing.JPanel();
        jAddButton = new javax.swing.JButton();
        jSubtractButton = new javax.swing.JButton();
        jMultiplyButton = new javax.swing.JButton();
        jDivideButton = new javax.swing.JButton();
        jCylinderButton = new javax.swing.JButton();
        jSphereButton = new javax.swing.JButton();
        jInput1Text = new javax.swing.JTextField();
        jInput2Text = new javax.swing.JTextField();
        jOutputText = new javax.swing.JTextField();
        jInput1Label = new javax.swing.JLabel();
        jInput2Label = new javax.swing.JLabel();
        jOutputLabel = new javax.swing.JLabel();
        jPyramidButton = new javax.swing.JButton();
        jPowerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jHeadOfficePanel = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jManagerName = new javax.swing.JTextField();
        jHours = new javax.swing.JTextField();
        jSortCode = new javax.swing.JTextField();
        jName = new javax.swing.JTextField();
        jHouseNumber = new javax.swing.JTextField();
        jStreet = new javax.swing.JTextField();
        jArea = new javax.swing.JTextField();
        jCity = new javax.swing.JTextField();
        jPostCode = new javax.swing.JTextField();
        jCountry = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jBranchInfoPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jHeadOfficeTextArea = new javax.swing.JTextArea();
        jShowInfoButton = new javax.swing.JButton();
        jClientsPanel = new javax.swing.JPanel();
        jAddClientButton = new javax.swing.JButton();
        jClientFirstName = new javax.swing.JTextField();
        jClientSurname = new javax.swing.JTextField();
        jClientAddressHouseName = new javax.swing.JTextField();
        jClientAddressName = new javax.swing.JTextField();
        jClientAddressHouseNumber = new javax.swing.JTextField();
        jClientAddressStreet = new javax.swing.JTextField();
        jClientAddressArea = new javax.swing.JTextField();
        jClientAddressCity = new javax.swing.JTextField();
        jClientAddressPostCode = new javax.swing.JTextField();
        jClientAddressCountry = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jClientRemoveTextField = new javax.swing.JTextField();
        jRemoveClientButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jClientBirthDate = new javax.swing.JTextField();
        jClientsInfoPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jClientsTextArea = new javax.swing.JTextArea();
        jShowClientsInfoButton = new javax.swing.JButton();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jStatusPanel.setBackground(new java.awt.Color(255, 0, 0));
        jStatusPanel.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N

        jStatusMessageLabel.setText("My first application is running");

        jStatusAnimationLabel.setBackground(new java.awt.Color(138, 43, 226));

        jNameLabel.setText("What is your name?");

        jNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameTextFieldActionPerformed(evt);
            }
        });

        jLoginButton.setText("Login");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        jPasswordLabel.setText("What is your password?");

        jRegisterButton.setText("Register");
        jRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterButtonActionPerformed(evt);
            }
        });

        jPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordTextFieldActionPerformed(evt);
            }
        });

        jPositionLabel.setText("Select Position:");

        jRoleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Administrator", "Client", "Advisor" }));
        jRoleBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRoleBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRoleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPositionLabel))
                        .addGap(127, 127, 127))
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordLabel)
                            .addGroup(jLoginPanelLayout.createSequentialGroup()
                                .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRegisterButton))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPositionLabel)
                    .addComponent(jNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLoginButton))
                        .addGap(32, 32, 32)
                        .addComponent(jPasswordLabel))
                    .addComponent(jRoleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRegisterButton))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Login", jLoginPanel);

        jAddButton.setText("+");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jSubtractButton.setText("-");
        jSubtractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubtractButtonActionPerformed(evt);
            }
        });

        jMultiplyButton.setText("*");
        jMultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMultiplyButtonActionPerformed(evt);
            }
        });

        jDivideButton.setText("/");
        jDivideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDivideButtonActionPerformed(evt);
            }
        });

        jCylinderButton.setText("Cylinder Volume");
        jCylinderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCylinderButtonActionPerformed(evt);
            }
        });

        jSphereButton.setText("Sphere Volume");
        jSphereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSphereButtonActionPerformed(evt);
            }
        });

        jInput1Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInput1TextActionPerformed(evt);
            }
        });

        jInput2Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInput2TextActionPerformed(evt);
            }
        });

        jOutputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOutputTextActionPerformed(evt);
            }
        });

        jInput1Label.setText("Input 1:");

        jInput2Label.setText("Input 2:");

        jOutputLabel.setText("Output:");

        jPyramidButton.setText("Square Based Pyramid Volume");
        jPyramidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPyramidButtonActionPerformed(evt);
            }
        });

        jPowerButton.setText("Power");
        jPowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPowerButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("lab 3");

        javax.swing.GroupLayout jCalculatorPanelLayout = new javax.swing.GroupLayout(jCalculatorPanel);
        jCalculatorPanel.setLayout(jCalculatorPanelLayout);
        jCalculatorPanelLayout.setHorizontalGroup(
            jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jAddButton)
                        .addGap(18, 18, 18)
                        .addComponent(jSubtractButton)
                        .addGap(18, 18, 18)
                        .addComponent(jMultiplyButton)
                        .addGap(18, 18, 18)
                        .addComponent(jDivideButton))
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPowerButton)
                        .addGap(18, 18, 18)
                        .addComponent(jCylinderButton)
                        .addGap(18, 18, 18)
                        .addComponent(jSphereButton)
                        .addGap(18, 18, 18)
                        .addComponent(jPyramidButton)))
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCalculatorPanelLayout.createSequentialGroup()
                        .addComponent(jInput1Label)
                        .addGap(18, 18, 18))
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addComponent(jInput2Label)
                        .addGap(18, 18, 18)))
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jInput2Text, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jInput1Text))
                .addGap(44, 44, 44)
                .addComponent(jOutputLabel)
                .addGap(18, 18, 18)
                .addComponent(jOutputText, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32))
        );
        jCalculatorPanelLayout.setVerticalGroup(
            jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jInput1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jInput1Label)
                            .addComponent(jOutputLabel)
                            .addComponent(jOutputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jInput2Label)
                            .addComponent(jInput2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addGap(30, 30, 30)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddButton)
                    .addComponent(jSubtractButton)
                    .addComponent(jMultiplyButton)
                    .addComponent(jDivideButton))
                .addGap(28, 28, 28)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCylinderButton)
                    .addComponent(jSphereButton)
                    .addComponent(jPyramidButton)
                    .addComponent(jPowerButton))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Calculator", jCalculatorPanel);

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCountryActionPerformed(evt);
            }
        });

        jLabel2.setText("Manager Name:");

        jLabel3.setText("Hours:");

        jLabel4.setText("Sort Code:");

        jLabel5.setText("Name:");

        jLabel6.setText("House Number:");

        jLabel7.setText("Street:");

        jLabel8.setText("Area:");

        jLabel9.setText("City:");

        jLabel10.setText("Post Code:");

        jLabel11.setText("Country:");

        javax.swing.GroupLayout jHeadOfficePanelLayout = new javax.swing.GroupLayout(jHeadOfficePanel);
        jHeadOfficePanel.setLayout(jHeadOfficePanelLayout);
        jHeadOfficePanelLayout.setHorizontalGroup(
            jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                        .addGap(545, 545, 545)
                        .addComponent(jButtonSave))
                    .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38)
                        .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jManagerName, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jHours)
                            .addComponent(jSortCode)
                            .addComponent(jName)
                            .addComponent(jHouseNumber))
                        .addGap(66, 66, 66)
                        .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addComponent(jLabel11))
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jStreet, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jArea)
                            .addComponent(jCity)
                            .addComponent(jPostCode)
                            .addComponent(jCountry))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jHeadOfficePanelLayout.setVerticalGroup(
            jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                        .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSortCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))))
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addComponent(jButtonSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Edit Head Office", jHeadOfficePanel);

        jHeadOfficeTextArea.setColumns(20);
        jHeadOfficeTextArea.setRows(5);
        jScrollPane2.setViewportView(jHeadOfficeTextArea);

        jShowInfoButton.setText("Show Information");
        jShowInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jBranchInfoPanelLayout = new javax.swing.GroupLayout(jBranchInfoPanel);
        jBranchInfoPanel.setLayout(jBranchInfoPanelLayout);
        jBranchInfoPanelLayout.setHorizontalGroup(
            jBranchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBranchInfoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jBranchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jShowInfoButton)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jBranchInfoPanelLayout.setVerticalGroup(
            jBranchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBranchInfoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(jShowInfoButton))
        );

        jMainTabbedPane.addTab("Head Office", jBranchInfoPanel);

        jAddClientButton.setText("Add");
        jAddClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddClientButtonActionPerformed(evt);
            }
        });

        jClientFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientFirstNameActionPerformed(evt);
            }
        });

        jClientAddressPostCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientAddressPostCodeActionPerformed(evt);
            }
        });

        jClientAddressCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientAddressCountryActionPerformed(evt);
            }
        });

        jLabel12.setText("First Name");

        jLabel13.setText("Surname");

        jLabel14.setText("House Name");

        jLabel15.setText("Name:");

        jLabel16.setText("House Number:");

        jLabel17.setText("Street:");

        jLabel18.setText("Area:");

        jLabel19.setText("City:");

        jLabel20.setText("Post Code:");

        jLabel21.setText("Country:");

        jLabel22.setText("Birth (MM/dd/yyyy):");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Delete Client");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Enter Surname of Client");

        jClientRemoveTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientRemoveTextFieldActionPerformed(evt);
            }
        });

        jRemoveClientButton.setText("Remove");
        jRemoveClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveClientButtonActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jClientsPanelLayout = new javax.swing.GroupLayout(jClientsPanel);
        jClientsPanel.setLayout(jClientsPanelLayout);
        jClientsPanelLayout.setHorizontalGroup(
            jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClientsPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jAddClientButton)
                    .addGroup(jClientsPanelLayout.createSequentialGroup()
                        .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(38, 38, 38)
                        .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jClientSurname)
                            .addComponent(jClientAddressHouseName)
                            .addComponent(jClientAddressName)
                            .addComponent(jClientAddressHouseNumber)
                            .addComponent(jClientFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jClientBirthDate))
                        .addGap(21, 21, 21)
                        .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addComponent(jLabel21))
                            .addComponent(jLabel18))
                        .addGap(32, 32, 32)
                        .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jClientAddressPostCode)
                            .addComponent(jClientAddressCountry)
                            .addComponent(jClientAddressStreet, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jClientAddressArea)
                            .addComponent(jClientAddressCity))))
                .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jClientsPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jClientRemoveTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jClientsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRemoveClientButton)))
                .addContainerGap())
        );
        jClientsPanelLayout.setVerticalGroup(
            jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClientsPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jClientsPanelLayout.createSequentialGroup()
                            .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jClientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jClientAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel17)
                                .addComponent(jLabel23))
                            .addGap(18, 18, 18)
                            .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jClientSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jClientAddressArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel18)
                                .addComponent(jLabel24))
                            .addGap(26, 26, 26)
                            .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jClientAddressHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jClientAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jClientRemoveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(20, 20, 20)
                            .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jClientAddressName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jClientAddressPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)))
                            .addGap(18, 18, 18)
                            .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jClientAddressHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jClientAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))))
                        .addComponent(jLabel16))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClientBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAddClientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRemoveClientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMainTabbedPane.addTab("Edit Clients", jClientsPanel);

        jClientsTextArea.setColumns(20);
        jClientsTextArea.setRows(5);
        jScrollPane3.setViewportView(jClientsTextArea);

        jShowClientsInfoButton.setText("Show Information");
        jShowClientsInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowClientsInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jClientsInfoPanelLayout = new javax.swing.GroupLayout(jClientsInfoPanel);
        jClientsInfoPanel.setLayout(jClientsInfoPanelLayout);
        jClientsInfoPanelLayout.setHorizontalGroup(
            jClientsInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClientsInfoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jClientsInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jShowClientsInfoButton)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jClientsInfoPanelLayout.setVerticalGroup(
            jClientsInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClientsInfoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(jShowClientsInfoButton))
        );

        jMainTabbedPane.addTab("Clients", jClientsInfoPanel);

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainTabbedPane))
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainTabbedPane)
                .addContainerGap())
        );

        jMainTabbedPane.getAccessibleContext().setAccessibleName("Calculator");

        javax.swing.GroupLayout jStatusPanelLayout = new javax.swing.GroupLayout(jStatusPanel);
        jStatusPanel.setLayout(jStatusPanelLayout);
        jStatusPanelLayout.setHorizontalGroup(
            jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jStatusPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressCompletionBar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jStatusPanelLayout.createSequentialGroup()
                        .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jStatusPanelLayout.createSequentialGroup()
                        .addComponent(jStatusMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jStatusAnimationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jStatusPanelLayout.setVerticalGroup(
            jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressCompletionBar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jStatusMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStatusAnimationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenuBarMain.setBackground(new java.awt.Color(39, 140, 230));
        jMenuBarMain.setBorder(new javax.swing.border.MatteBorder(null));

        jMenu1.setText("File");
        jMenuBarMain.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBarMain.add(jMenu2);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jStatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jStatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        if ("Manager".equals(theUser.getRole(jNameTextField.getText(), jPasswordTextField.getText()))) {
            theHeadOfficeBranch.Edit(jManagerName.getText(), jSortCode.getText(), jHours.getText());
            theHeadOfficeBranch.EditAddress(jName.getText(), jStreet.getText(), HEIGHT, jArea.getText(), jPostCode.getText(), jCity.getText(), jCountry.getText(), " ");
            theHeadOfficeBranch.SaveToFile(true);
        }

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jPowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPowerButtonActionPerformed
        double input1 = Double.valueOf(jInput1Text.getText());
        double input2 = Double.valueOf(jInput2Text.getText());

        long output = 1;
        for (; input2 != 0; --input2) {
            output *= input1;
        }

        jOutputText.setText(String.valueOf(output));
    }//GEN-LAST:event_jPowerButtonActionPerformed

    private void jPyramidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPyramidButtonActionPerformed
        double input1 = Double.valueOf(jInput1Text.getText());
        double input2 = Double.valueOf(jInput2Text.getText());

        double output = input1 * input1 * (input2 / 3);
        jOutputText.setText(String.valueOf(output));
    }//GEN-LAST:event_jPyramidButtonActionPerformed

    private void jOutputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOutputTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOutputTextActionPerformed

    private void jInput2TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInput2TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInput2TextActionPerformed

    private void jInput1TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInput1TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInput1TextActionPerformed

    private void jSphereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSphereButtonActionPerformed
        double input1 = Double.valueOf(jInput1Text.getText());
        double input2 = Double.valueOf(jInput2Text.getText());

        double output = 3.141592653589793238 * input1 * input1 * input1 * 1.33333333334;
        jOutputText.setText(String.valueOf(output));
    }//GEN-LAST:event_jSphereButtonActionPerformed

    private void jCylinderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCylinderButtonActionPerformed
        double input1 = Double.valueOf(jInput1Text.getText());
        double input2 = Double.valueOf(jInput2Text.getText());

        double output = 3.141592653589793238 * (input1 * input1) * input2;
        jOutputText.setText(String.valueOf(output));
    }//GEN-LAST:event_jCylinderButtonActionPerformed

    private void jDivideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDivideButtonActionPerformed
        double input1 = Double.valueOf(jInput1Text.getText());
        double input2 = Double.valueOf(jInput2Text.getText());

        if (input2 == 0) {
            jOutputText.setText("No, Math Error");
        } else {
            double output = input1 / input2;

            jOutputText.setText(String.valueOf(output));
        }
    }//GEN-LAST:event_jDivideButtonActionPerformed

    private void jMultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMultiplyButtonActionPerformed
        double input1 = Double.valueOf(jInput1Text.getText());
        double input2 = Double.valueOf(jInput2Text.getText());

        double output = input1 * input2;
        jOutputText.setText(String.valueOf(output));
    }//GEN-LAST:event_jMultiplyButtonActionPerformed

    private void jSubtractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubtractButtonActionPerformed
        double input1 = Double.valueOf(jInput1Text.getText());
        double input2 = Double.valueOf(jInput2Text.getText());

        double output = input1 - input2;
        jOutputText.setText(String.valueOf(output));
    }//GEN-LAST:event_jSubtractButtonActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        double input1 = Double.valueOf(jInput1Text.getText());
        double input2 = Double.valueOf(jInput2Text.getText());

        double output = input1 + input2;
        jOutputText.setText(String.valueOf(output));
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jRoleBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRoleBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRoleBoxActionPerformed

    private void jPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordTextFieldActionPerformed

    private void jRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterButtonActionPerformed
        // TODO add your handling code here:
        if (theUser.usernameunique(jNameTextField.getText())) {

            if (!theUser.isRegistered(jNameTextField.getText(), jPasswordTextField.getText(), (String) jRoleBox.getSelectedItem())) {
                jStatusMessageLabel.setText("cannot register...");
            } else {
                jStatusMessageLabel.setText("the user is registered pls log in ");
            }
        } else {
            jStatusMessageLabel.setText("the" + jNameTextField.getText() + "is registered pls login.");
        }
    }//GEN-LAST:event_jRegisterButtonActionPerformed

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        if (theUser.isUser(jNameTextField.getText(), jPasswordTextField.getText())) {
            jStatusMessageLabel.setText(jNameTextField.getText() + " is logged in...");
            if ("Manager".equals(theUser.getRole(jNameTextField.getText(), jPasswordTextField.getText()))) {
                jMainTabbedPane.addTab("Calculator", jCalcTabInMemory);
                jMainTabbedPane.addTab("Edit Head Office", jHeadOfficeTabInMemory);
                jMainTabbedPane.addTab("Head Office", jEditHeadOfficeTabInMemory);
                jMainTabbedPane.addTab("Edit Clients", jEditClientTabInMemory);
                jMainTabbedPane.addTab("Clients", jClientInfoTabInMemory);

            } else if ("Administrator".equals(theUser.getRole(jNameTextField.getText(), jPasswordTextField.getText()))) {
                jMainTabbedPane.addTab("Calculator", jCalcTabInMemory);
                jMainTabbedPane.addTab("Edit Head Office", jHeadOfficeTabInMemory);
                jMainTabbedPane.addTab("Head Office", jEditHeadOfficeTabInMemory);
                jMainTabbedPane.addTab("Edit Clients", jEditClientTabInMemory);
                jMainTabbedPane.addTab("Clients", jClientInfoTabInMemory);
            } else if ("Advisor".equals(theUser.getRole(jNameTextField.getText(), jPasswordTextField.getText()))) {
                jMainTabbedPane.addTab("Calculator", jCalcTabInMemory);
                jMainTabbedPane.addTab("Head Office", jEditHeadOfficeTabInMemory);
                jMainTabbedPane.addTab("Clients", jClientInfoTabInMemory);

            } else if ("Client".equals(theUser.getRole(jNameTextField.getText(), jPasswordTextField.getText()))) {
                jMainTabbedPane.addTab("Calculator", jCalcTabInMemory);
                jMainTabbedPane.addTab("Head Office", jEditHeadOfficeTabInMemory);
                jMainTabbedPane.addTab("Clients", jClientInfoTabInMemory);
            }
            jMainTabbedPane.setSelectedIndex(1);

        }
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void jNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameTextFieldActionPerformed

    private void jShowInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowInfoButtonActionPerformed
        // TODO add your handling code here:
        theHeadOfficeBranch.Display(jHeadOfficeTextArea);
        theHeadOfficeBranch.DisplayAddress(jHeadOfficeTextArea);
    }//GEN-LAST:event_jShowInfoButtonActionPerformed

    private void jCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCountryActionPerformed

    private void jShowClientsInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowClientsInfoButtonActionPerformed
        this.clientsList.loadFromFile();
        System.out.println("Clients after load: "+this.clientsList.size());
        jClientsTextArea.setText("");
        this.clientsList.Display(jClientsTextArea);
    }//GEN-LAST:event_jShowClientsInfoButtonActionPerformed

    private void jAddClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddClientButtonActionPerformed
        String name, housename, street, area, postcode, town, country;
        int houseno;
        String firstname, surname;
        Date dob =null, customerSince;
        firstname = jClientFirstName.getText();
        surname = jClientSurname.getText();
        try {
            dob = Customer.sdf.parse(jClientBirthDate.getText().trim());
        } catch (ParseException ex) {
            System.out.println("Date Exception: "+ex.getMessage());
        }
        customerSince = new Date();

        houseno = Integer.parseInt(jClientAddressHouseNumber.getText());
        housename = jClientAddressHouseName.getText();
        name = jClientAddressName.getText();
        street = jClientAddressStreet.getText();
        area = jClientAddressArea.getText();
        postcode = jClientAddressHouseName.getText();
        town = jClientAddressArea.getText();
        country = jClientAddressCountry.getText();
        Customer c = new Customer(firstname, surname, dob, customerSince);
        c.EditAddress(name, street, houseno, housename, area, postcode, town, country);
        this.clientsList.add(c);
        this.clientsList.saveToFile();
        clearClientFields();

    }//GEN-LAST:event_jAddClientButtonActionPerformed

    private void clearClientFields(){
    
        this.jClientFirstName.setText("");
        this.jClientSurname.setText("");
        this.jClientBirthDate.setText("");
        
        this.jClientAddressName.setText("");
        this.jClientAddressCity.setText("");
        this.jClientAddressCountry.setText("");
        this.jClientAddressHouseNumber.setText("");
        this.jClientAddressArea.setText("");
        this.jClientAddressHouseName.setText("");
        this.jClientAddressPostCode.setText("");
        this.jClientAddressStreet.setText("");
        this.jClientAddressHouseName.setText("");
        
        
        
    
    }
    
    private void jClientAddressCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientAddressCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClientAddressCountryActionPerformed

    private void jRemoveClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveClientButtonActionPerformed
       String surnameToRemove =  jClientRemoveTextField.getText().trim();
       if(surnameToRemove.length()>0){
           Customer c = this.clientsList.remove(surnameToRemove);
           if(c !=null){
               jClientRemoveTextField.setText("");
           }
       }
    }//GEN-LAST:event_jRemoveClientButtonActionPerformed

    private void jClientFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClientFirstNameActionPerformed

    private void jClientRemoveTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientRemoveTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClientRemoveTextFieldActionPerformed

    private void jClientAddressPostCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientAddressPostCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClientAddressPostCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    //Declaration of object theHeadOfficeBranch type of Branch
    private java.awt.Component jCalcTabInMemory;
    private java.awt.Component jHeadOfficeTabInMemory;
    private java.awt.Component jEditHeadOfficeTabInMemory;
    private java.awt.Component jEditClientTabInMemory;
    private java.awt.Component jClientInfoTabInMemory;

    private CustomerList clientsList;
    private Branch theHeadOfficeBranch;
    private IAddress theAddress;
    private User theUser;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jAddClientButton;
    private javax.swing.JTextField jArea;
    private javax.swing.JPanel jBranchInfoPanel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JPanel jCalculatorPanel;
    private javax.swing.JTextField jCity;
    private javax.swing.JTextField jClientAddressArea;
    private javax.swing.JTextField jClientAddressCity;
    private javax.swing.JTextField jClientAddressCountry;
    private javax.swing.JTextField jClientAddressHouseName;
    private javax.swing.JTextField jClientAddressHouseNumber;
    private javax.swing.JTextField jClientAddressName;
    private javax.swing.JTextField jClientAddressPostCode;
    private javax.swing.JTextField jClientAddressStreet;
    private javax.swing.JTextField jClientBirthDate;
    private javax.swing.JTextField jClientFirstName;
    private javax.swing.JTextField jClientRemoveTextField;
    private javax.swing.JTextField jClientSurname;
    private javax.swing.JPanel jClientsInfoPanel;
    private javax.swing.JPanel jClientsPanel;
    private javax.swing.JTextArea jClientsTextArea;
    private javax.swing.JTextField jCountry;
    private javax.swing.JButton jCylinderButton;
    private javax.swing.JButton jDivideButton;
    private javax.swing.JPanel jHeadOfficePanel;
    private javax.swing.JTextArea jHeadOfficeTextArea;
    private javax.swing.JTextField jHours;
    private javax.swing.JTextField jHouseNumber;
    private javax.swing.JLabel jInput1Label;
    private javax.swing.JTextField jInput1Text;
    private javax.swing.JLabel jInput2Label;
    private javax.swing.JTextField jInput2Text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JTabbedPane jMainTabbedPane;
    private javax.swing.JTextField jManagerName;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JButton jMultiplyButton;
    private javax.swing.JTextField jName;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JTextField jNameTextField;
    private javax.swing.JLabel jOutputLabel;
    private javax.swing.JTextField jOutputText;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JTextField jPasswordTextField;
    private javax.swing.JLabel jPositionLabel;
    private javax.swing.JTextField jPostCode;
    private javax.swing.JButton jPowerButton;
    private javax.swing.JProgressBar jProgressCompletionBar;
    private javax.swing.JButton jPyramidButton;
    private javax.swing.JButton jRegisterButton;
    private javax.swing.JButton jRemoveClientButton;
    private javax.swing.JComboBox<String> jRoleBox;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jShowClientsInfoButton;
    private javax.swing.JButton jShowInfoButton;
    private javax.swing.JTextField jSortCode;
    private javax.swing.JButton jSphereButton;
    private javax.swing.JLabel jStatusAnimationLabel;
    private javax.swing.JLabel jStatusMessageLabel;
    private javax.swing.JPanel jStatusPanel;
    private javax.swing.JTextField jStreet;
    private javax.swing.JButton jSubtractButton;
    // End of variables declaration//GEN-END:variables
}
